---
- name: install open-iscsi
  portage: package=sys-block/open-iscsi

- name: install sg3_utils, lsscsi and multipath-tools
  portage: package={{ item }}
  with_items:
    - sys-apps/sg3_utils
    - sys-fs/lsscsi
    - sys-fs/multipath-tools
  when: iscsi_multipath_enabled | bool

- include: iscsi.yml

- include: multipath.yml
  when: iscsi_multipath_enabled | bool
